apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: web
  targetNamespace: default
  chart:
    git: git@github.com:latchdeen/fluxd-helm-k8s.git
    path: fluxd-helm-k8s/web/
    ref: master
