apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: web
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: web
  targetNamespace: default
  chart:
    git: https://github.com/latchdeen/fluxd-helm-k8s.git
    path: web
    ref: master
